### ISSUE TITLE
Functions/Utilities Recommendation: Neural Network visualization tools

### ISSUE THREAD

**Issue by ZedaX7** [cmudrc/drcutils#1]
Functions/Utilities Recommendation: Neural Network visualization tools. Some functions or tools to visualize different types of Neural Networks would be great! (Struggling to find good ways to visualize LSTMs. )

**Comment by cmccomb** [comment]
Are you talking about visualizing the architecture of the NN?

**Comment by ZedaX7** [comment]
> Member

Yes!

**Comment by cmccomb** [comment]
This doesn't solve the problem in a programmatic way but its pretty awesome: https://netron.app/

**Comment by cmccomb** [comment]
https://github.com/ashishpatel26/Tools-to-Design-or-Visualize-Architecture-of-Neural-Network

**Comment by cmccomb** [comment]
@ZedaX7, how does this look? 
<img width="1016" alt="Screenshot 2022-12-17 at 1 58 25 PM" src="https://user-images.githubusercontent.com/6705753/208257417-7c6d470e-714f-455c-9ed0-22912934e710.png">

**Comment by ZedaX7** [comment]
The GitHub one is definitely the best-looking one! I found similar repositories before but I could find any good visualization methods/tools for the LSTM models. Most of the tools are built for CNNs, which arguably is easier to visualize due to the model structure. Anyway, these are all very useful tools! Thanks!!
